version: "3"
services:
  cliapp:
    build:
      context: ./
      dockerfile: Dockerfile.cliapp
    volumes: 
      - chimera_volume:/opt/chimera/data
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile.webapp
    ports:
      - "5000:80"
    volumes: 
     - chimera_volume:/opt/chimera/data
volumes: 
  chimera_volume: null


